# frozen_string_literal: true

Style/InlineComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/SlicingWithRange:
  Enabled: false

Metric/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
