# frozen_string_literal: true
source('https://rubygems.org')

source('https://rubygems.org') do
  gem('bundler', '~> 2.1.4')
  gem('pry', '~> 0.14.1')
  gem('readline', '~> 0.0.3')
  gem('require_all', '~> 3.0.0')
  gem('rubocop', '~> 1.38.0')
  gem('serialport', '~> 1.3.2')
end
